ALTER TABLE public.bank_config ADD CONSTRAINT bank_config_pkey PRIMARY KEY (id);
ALTER TABLE public.group_payment_requests ADD CONSTRAINT group_payment_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.group_payment_requests ADD CONSTRAINT group_payment_requests_group_code_key UNIQUE (group_code);
ALTER TABLE public.members ADD CONSTRAINT members_pkey PRIMARY KEY (id);
ALTER TABLE public.sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.session_intervals ADD CONSTRAINT session_intervals_pkey PRIMARY KEY (id);
ALTER TABLE public.session_registrations ADD CONSTRAINT session_registrations_pkey PRIMARY KEY (id);
ALTER TABLE public.session_registrations ADD CONSTRAINT session_registrations_session_id_member_id_key UNIQUE (session_id, member_id);
ALTER TABLE public.interval_presence ADD CONSTRAINT interval_presence_pkey PRIMARY KEY (id);
ALTER TABLE public.interval_presence ADD CONSTRAINT interval_presence_interval_id_member_id_key UNIQUE (interval_id, member_id);
ALTER TABLE public.session_costs_snapshot ADD CONSTRAINT session_costs_snapshot_pkey PRIMARY KEY (id);
ALTER TABLE public.session_costs_snapshot ADD CONSTRAINT session_costs_snapshot_payment_code_key UNIQUE (payment_code);
ALTER TABLE public.session_costs_snapshot ADD CONSTRAINT session_costs_snapshot_session_id_member_id_key UNIQUE (session_id, member_id);
ALTER TABLE public.session_payments ADD CONSTRAINT session_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.session_payments ADD CONSTRAINT session_payments_transaction_id_key UNIQUE (transaction_id);
ALTER TABLE public.session_court_bookings ADD CONSTRAINT session_court_bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.session_extra_charges ADD CONSTRAINT session_extra_charges_pkey PRIMARY KEY (id);

ALTER TABLE public.members ADD CONSTRAINT members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.session_intervals ADD CONSTRAINT session_intervals_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.session_registrations ADD CONSTRAINT session_registrations_member_id_fkey FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.session_registrations ADD CONSTRAINT session_registrations_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.interval_presence ADD CONSTRAINT interval_presence_interval_id_fkey FOREIGN KEY (interval_id) REFERENCES session_intervals(id) ON DELETE CASCADE;
ALTER TABLE public.interval_presence ADD CONSTRAINT interval_presence_member_id_fkey FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.session_costs_snapshot ADD CONSTRAINT session_costs_snapshot_member_id_fkey FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE public.session_costs_snapshot ADD CONSTRAINT session_costs_snapshot_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id);
ALTER TABLE public.session_payments ADD CONSTRAINT session_payments_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES session_costs_snapshot(id);
ALTER TABLE public.session_court_bookings ADD CONSTRAINT session_court_bookings_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
ALTER TABLE public.session_extra_charges ADD CONSTRAINT session_extra_charges_member_id_fkey FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE;
ALTER TABLE public.session_extra_charges ADD CONSTRAINT session_extra_charges_session_id_fkey FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;
